project:
  type: website

website:
  title: "Sommerfest Ausgabe 2026"
  navbar: 
    left: 
      - text: "Programm"
        href: "Programm.qmd"
      - text: "Anreise"
        href: "anreise.qmd"
    right: 
      - text: "Ausgabe 2024"
        href: "2024.qmd"

lang: de-CH
format:
  html:
    theme: sketchy #quartz #minty # lumen, 
    css: styles.css



