---
title: Ausflug
alias: 
    - ausflug
    - Ausflug
---

- 11:00 Uhr vom Festgelände los laufen
- 11:22 Bus in Wädenswil, Feld (Nils besorgt Tickets zum abstempeln), siehe [SBB](https://www.sbb.ch/de?stops=W%C3%A4denswil%2C+Feld_I8573570%7ESch%C3%B6nenberg+ZH%2C+Dorfhuus_I8596115&day=2026-07-24&time=10_12&moment=dep&trip=0_2)
- 11:27 Ankunft Schönenberg, Dorfhuus
- Gemütliche Wanderung (5.5km, Details siehe unten) 
- 13:59 Optionale Rückfahrt ab *Schönenberg, Müsli* ([SBB](https://www.sbb.ch/de?stops=Sch%C3%B6nenberg+ZH%2C+M%C3%BCsli_I8503897%7EW%C3%A4denswil%2C+Feld_I8573570&day=2026-07-24&time=15_00&moment=arr&trip=0_4)) für alle, die genug haben und früh Zuhause sein möchten.
- 16:05 "Offizielle" Rückfahrt ab *Schönenberg, Müsli* ([SBB](https://www.sbb.ch/de?stops=Sch%C3%B6nenberg+ZH%2C+M%C3%BCsli_I8503897%7EW%C3%A4denswil%2C+Feld_I8573570&day=2026-07-24&time=15_00&moment=arr&trip=1_0&cursor=M3xPRnxNVMK1MTTCtTMyMzM5OcK1MzIzMzk5wrUzMjM0MzTCtTMyMzQzNMK1MMK1MMK1NMK1MzIzNDYwwrUtMcK1MMK1MTjCtTDCtTDCtTDCtTHCtTF8UERIwrUzMjhmMmIyNDdjNjg2MjU2OTMxM2E4MDA5OGM3YTE5NXxSRMK1MjQwNzIwMjZ8UlTCtTE1MDAwMHxVU8K1MHxSU8K1SU5JVA%3D%3D))


Ein paar Hinweise zur Wanderstrecke:

- Für die 5.5km haben wir 2 resp. 4 Stunden eingeplant. Das Tempo ist also sehr gemächlich und auch für Kinder geeignet. Wir nehmen auch ein Bollerwagen ([Ulfbo](images/ulfbo.png)) mit, wo kleinere Kinder sich abwechseln ausruhen können. 
- Die Strecke ist sehr bedingt kinderwagen Tauglich (nur mit dicken Offroad reifen und genügend Helfer). 
- Auf der Strecke befindet sich das [Restaurant Sihlmatt](https://maps.app.goo.gl/QnNmiE5QRhbFtFUR8), wo man sich ein Eis oder Bierchen kaufen kann.
- Es gibt auf der Strecken eine schöne Badestelle zum Verweilen (nähe [Sihlsprung](https://maps.app.goo.gl/PLtVbZ7Xjs3zY3P27)). 

<iframe src="https://www.komoot.com/tour/3128449715/embed?share_token=aPhMReZuJU9vDJJ4FHzh5JvVGo7gmtfiLQJ2sZAp8fP559aSnK&amp;layout=classic&amp;profile=1" width="100%" height="700" frameborder="0" scrolling="no"></iframe>